default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DEV_AM_DB_NAME'] %>

test:
  <<: *default
  database: <%= ENV['TEST_AM_DB_NAME'] %>

production:
  <<: *default
  database: <%= ENV['PROD_AM_DB_NAME'] %>